linters:
  enable-all: true
  disable:
    - exhaustruct
    - ireturn
    - depguard
    - lll
    - nonamedreturns
    - forcetypeassert
    - varnamelen
    - tagliatelle
    - perfsprint
    - noctx
    - forbidigo

run:
  tests: false