apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cisin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cisin
subjects:
  - kind: ServiceAccount
    name: cisin
    namespace: cisin
