apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cisin
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ""
      - "apps"
    resources:
      - pods
      - replicasets