apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: grpc
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: http
    - protocol: TCP
      port: 8080
      targetPort: 16686
      name: ui
  type: ClusterIP