{
 "title": "CISIN CVEs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CVEs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(cisin_workload_cve)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CVEs by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cisin_workload_cve) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "CVE Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "cisin_workload_cve", "legendFormat": "__auto" }
   ]
  }
 ]
}